// templates/vue/files/src/App.vue
<script setup>
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="app">
    <h1>🚀 {{projectName}}</h1>
    <p>Welcome to your new Vue project!</p>
    <div class="card">
      <button @click="count++">
        Count: {{ count }}
      </button>
    </div>
  </div>
</template>

<style scoped>
.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}
</style>

// my-ci-app/src/App.jsx
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <h1>my-ci-app</h1>
      <p>Welcome to your new React project!</p>
      <div className="card">
        <button onClick={() => setCount((c) => c + 1)}>
          Count: {count}
        </button>
      </div>
    </div>
  );
}

export default App;
